import type { Match } from '../types/match.types';

export const navLinks = [
  { to: '/', label: 'Dashboard' },
  { to: '/matches', label: 'Matches' },
  { to: '/favorites', label: 'Favorites' },
];

export const suggestedPrompts = [
  'Who is most likely to win tonight?',
  'Show me the closest odds on the board.',
  'Which match has the highest confidence score?',
];

export const demoMatches: Match[] = [
  {
    id: 'm1',
    sport: 'Basketball',
    league: 'NBA',
    teamA: 'Golden State Warriors',
    teamB: 'Phoenix Suns',
    teamARating: 88,
    teamBRating: 84,
    startTime: '2026-04-08T19:30:00.000Z',
    status: 'live',
    homeAdvantage: true,
    recentForm: [1, 1, 0, 1, 1],
    headToHead: { teamAWins: 6, teamBWins: 4 },
    odds: {
      teamAWinProb: 0.54,
      teamBWinProb: 0.36,
      drawProb: 0.1,
      odds: { teamA: 1.84, teamB: 2.68, draw: 8.5 },
      confidenceScore: 0.86,
      factors: ['Warriors home edge', 'Recent form favors Warriors', 'Stable closing line'],
    },
  },
  {
    id: 'm2',
    sport: 'Football',
    league: 'Premier League',
    teamA: 'Manchester City',
    teamB: 'Arsenal',
    teamARating: 92,
    teamBRating: 90,
    startTime: '2026-04-08T17:00:00.000Z',
    status: 'scheduled',
    homeAdvantage: true,
    recentForm: [1, 1, 1, 0, 1],
    headToHead: { teamAWins: 5, teamBWins: 3 },
    odds: {
      teamAWinProb: 0.44,
      teamBWinProb: 0.33,
      drawProb: 0.23,
      odds: { teamA: 2.15, teamB: 2.86, draw: 3.82 },
      confidenceScore: 0.72,
      factors: ['Elite attacking rating on both sides', 'Small home advantage for City'],
    },
  },
  {
    id: 'm3',
    sport: 'Football',
    league: 'NFL',
    teamA: 'Kansas City Chiefs',
    teamB: 'Buffalo Bills',
    teamARating: 93,
    teamBRating: 91,
    startTime: '2026-04-09T00:20:00.000Z',
    status: 'scheduled',
    homeAdvantage: false,
    recentForm: [1, 0, 1, 1, 1],
    headToHead: { teamAWins: 4, teamBWins: 4 },
    odds: {
      teamAWinProb: 0.49,
      teamBWinProb: 0.45,
      drawProb: 0.06,
      odds: { teamA: 1.99, teamB: 2.08, draw: 14.7 },
      confidenceScore: 0.66,
      factors: ['Very close team ratings', 'Minimal separation in recent form'],
    },
  },
  {
    id: 'm4',
    sport: 'Football',
    league: 'UEFA Champions League',
    teamA: 'Real Madrid',
    teamB: 'Inter Milan',
    teamARating: 90,
    teamBRating: 85,
    startTime: '2026-04-10T19:00:00.000Z',
    status: 'scheduled',
    homeAdvantage: true,
    recentForm: [1, 1, 1, 1, 0],
    headToHead: { teamAWins: 7, teamBWins: 2 },
    odds: {
      teamAWinProb: 0.57,
      teamBWinProb: 0.24,
      drawProb: 0.19,
      odds: { teamA: 1.73, teamB: 4.11, draw: 4.56 },
      confidenceScore: 0.91,
      factors: ['Strong Elo gap', 'Home crowd boost', 'Positive head-to-head record'],
    },
  },
];
